### ISSUE TITLE
Consensus Sequence

### ISSUE THREAD

**Issue by j23414** [zbwrnz/smof#3]
Any thoughts on `smof` being able to output a consensus sequence when given an alignment file? 

**input fasta**

```
>seq_1
AAATATAT
>seq_2
AAAATTAT
>seq_3
AAATATAA
```

**output fasta**

```
>Consensus
AAATATAT
```

**Comment by arendsee** [comment]
@j23414 Thanks for the suggestion. It's a fine idea and I think falls within the intended scope of `smof`. I'll put it on the TODO list.

**Comment by arendsee** [comment]
I've partially implemented a consensus function over on the dev branch. You can check out the comment in the commit message.

The current output is a table of character counts across the columns in the alignment. But if we want to go from this table to a single consensus string, we will need to decide how to resolve ties.

**Comment by j23414** [comment]
For ties, would it make sense to output both options (both consensus sequences)? 

Although I could see that becoming many consensus sequences (ties in more than 1 position)...

**Comment by arendsee** [comment]
I can't do that in FASTA format.

Perhaps if there is a near tie, I could use a wildcard, like `*`. For cutoff, I could use Shannon entropy. This is the standard measure conservation used in LOGO plots and the like.

**Comment by j23414** [comment]
As a standard input for LOGO plots would be acceptable. 

By multiple consensuses I'm talking about:

```
>consensus_1
AATATAT
>consensus_2
AAAATAT
```

I'm looking at influenza virus sequence which group as H1.alpha, H1.beta, H1.gamma, etc...
I need the consensus for each group (alpha, beta, gamma... ) and am aligning their consensus(es) so I can determine their major nucleotide (or amino acid) differences between groups.

This might explain why a vaccine works for alpha (targets certain amino acids), but not for gamma, etc...

No worries either way, I can work with the table of character counts. : )

**Comment by arendsee** [comment]
Hmm, I'd worry about a combinatorial explosion.

**Comment by arendsee** [comment]
@j23414 You can check out the lastest version (2.13.0) of `smof`. Now the `consensus` command prints the consensus (resolving ties alphabetically) by default. Printing a table is optional.

Is good?

**Comment by j23414** [comment]
Good! : ) Consensus and table look good.

```
smof consensus fasta_aln.fna > consensus.fna
smof consensus -t fasta_aln.fna > consensus.tsv
```
