### ISSUE TITLE
Standard input incorrect when including subcommand flags

### ISSUE THREAD

**Issue by btski** [zbwrnz/smof#6]
I tried to use `cat test.fasta | smof grep -f test.txt` and got a "ShitInput" error. This only occurs when a subcommand flag is invoked when trying to pipe from standard input. I added `default=sys.stdin` to all file arguments. I then encountered `TypeError: can only concatenate list (not "_io.TextIOWrapper") to list` in the [main function](https://github.com/incertae-sedis/smof/blob/1a0be0e96af0907a71ea1fbca5c6357d71a92cff/smof/ui.py#L1870). This was simply resolved by overwriting fh entirely instead of appending. Since the default value of fh is now standard input, appending text is not compatible. I also considered the [additional conditionals](https://github.com/incertae-sedis/smof/blob/1a0be0e96af0907a71ea1fbca5c6357d71a92cff/smof/ui.py#L1869) to be unnecessary. 

Created pull request #5 with proposed solution. Tested with the following:
 `cat test.fasta | smof grep -f test.txt`
`smof grep -f test.txt test.fasta`

**Comment by arendsee** [comment]
Ah, quite right. I'll accept the pull request. Thanks!

I should probably remove that shit also.
